services/web/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.schemas import get_schema_view
from api import views

urlpatterns = [
    path("persons/", views.PersonList.as_view(), name="api-person-list"),
    path("persons/<int:pk>/", views.PersonDetail.as_view(), name="api-person-detail"),
    path(
        "organisations/", views.OrganisationList.as_view(), name="api-organisation-list"
    ),
    path(
        "organisations/<int:pk>/",
        views.OrganisationDetail.as_view(),
        name="api-organisation-detail",
    ),
    path("projects/", views.ProjectList.as_view(), name="api-project-list"),
    path(
        "projects/<int:pk>/", views.ProjectDetail.as_view(), name="api-project-detail"
    ),
    path(
        "openapi",
        get_schema_view(
            title="CoPED",
            description="Catalogue of Projects on Energy Data",
            version="1.0.0",
        ),
        name="openapi-schema",
    ),
    path("", views.api_root, name="api-root"),
]

services/web/core/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path

# from core import views
# from core.models import project
from core.views import (
    action_view,
    address,
    announcement,
    favourite,
    keyword,
    link,
    message,
    organisation,
    page_view,
    person,
    project,
    subject,
    suggestion_view,
    user,
)
from django.contrib.sitemaps.views import sitemap
from .sitemaps import ProjectSitemap
from django_registration.backends.activation.views import RegistrationView

from .forms import CustomUserForm

app_name = "core"
sitemaps = {"project": ProjectSitemap}

## Settings for admin

admin.site.site_header = "CoPED Adminstration"

urlpatterns = [
    #
    #
    ###############
    ## SUB-PATHS ##
    ###############
    #
    path("__debug__/", include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("select2/", include("django_select2.urls")),
    path("invitations/", include("invitations.urls", namespace="invitations")),
    path(
        "accounts/register/",
        RegistrationView.as_view(form_class=CustomUserForm),
        name="django_registration_register",
    ),
    path(
        "accounts/activate/resend/",
        user.UserResendActivationEmailView.as_view(),
        name="resend-activation-email",
    ),
    path("accounts/", include("django_registration.backends.activation.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path(
        "projects/<int:pk>/request-data-change/",
        message.ProjectRequestDataChangeView.as_view(),
        name="project-request-data-change",
    ),
    path(
        "projects/<int:pk>/claim-ownership/",
        message.ProjectClaimOwnershipView.as_view(),
        name="project-claim-ownership",
    ),
    path(
        "projects/<int:pk>/contact-owner/",
        message.ProjectContactOwnerView.as_view(),
        name="project-contact-owner",
    ),
    path(
        "projects/<int:pk>/favourite/",
        action_view.favourite_project,
        name="project-favourite",
    ),
    path(
        "projects/<int:pk>/unsubscribe/",
        action_view.unfavourite_project,
        name="project-unfavourite",
    ),
    path("messages/inbox/", message.InboxView.as_view(), name="pinax_messages:inbox"),
    path("messages/", include("pinax.messages.urls", namespace="pinax_messages")),
    path(
        "announcements/",
        announcement.AnnouncementListView.as_view(),
        name="pinax_announcements:announcement_list",
    ),
    path(
        "announcements/propose/",
        message.ProposeAnnouncementView.as_view(),
        name="propose-announcement",
    ),
    path(
        "announcements/",
        include("pinax.announcements.urls", namespace="pinax_announcements"),
    ),
    #
    #
    ############
    ## PEOPLE ##
    ############
    #
    path("people/suggest/", suggestion_view.person_suggest, name="person-suggest"),
    path(
        "people/<int:pk>/",
        person.PersonDetailView.as_view(),
        name="person-detail",
    ),
    path("people/", person.PersonListView.as_view(), name="person-list"),
    path("people/create/", person.PersonCreateView.as_view(), name="person-create"),
    path(
        "people/<int:pk>/update/",
        person.PersonUpdateView.as_view(),
        name="person-update",
    ),
    path(
        "people/<int:pk>/delete/",
        person.PersonDeleteView.as_view(),
        name="person-delete",
    ),
    path(
        "people/<int:pk>/request-data-change/",
        message.PersonRequestDataChangeView.as_view(),
        name="person-request-data-change",
    ),
    path(
        "people/<int:pk>/claim-ownership/",
        message.PersonClaimOwnershipView.as_view(),
        name="person-claim-ownership",
    ),
    path(
        "people/<int:pk>/contact-owner/",
        message.PersonContactOwnerView.as_view(),
        name="person-contact-owner",
    ),
    path(
        "people/<int:pk>/favourite/",
        action_view.favourite_person,
        name="person-favourite",
    ),
    path(
        "people/<int:pk>/unsubscribe/",
        action_view.unfavourite_person,
        name="person-unfavourite",
    ),
    #
    #
    ###################
    ## ORGANISATIONS ##
    ###################
    #
    path(
        "organisations/suggest/",
        suggestion_view.organisation_suggest,
        name="organisation-suggest",
    ),
    path(
        "organisations/<int:pk>/",
        organisation.OrganisationDetailView.as_view(),
        name="organisation-detail",
    ),
    path(
        "organisations/<int:pk>/update/",
        organisation.OrganisationUpdateView.as_view(),
        name="organisation-update",
    ),
    path(
        "organisations/",
        organisation.OrganisationListView.as_view(),
        name="organisation-list",
    ),
    path(
        "organisations/create/",
        organisation.OrganisationCreateView.as_view(),
        name="organisation-create",
    ),
    path(
        "organisation/<int:pk>/delete/",
        organisation.OrganisationDeleteView.as_view(),
        name="organisation-delete",
    ),
    path(
        "organisation/<int:pk>/request-data-change/",
        message.OrganisationRequestDataChangeView.as_view(),
        name="organisation-request-data-change",
    ),
    path(
        "organisation/<int:pk>/claim-ownership/",
        message.OrganisationClaimOwnershipView.as_view(),
        name="organisation-claim-ownership",
    ),
    path(
        "organisation/<int:pk>/contact-owner/",
        message.OrganisationContactOwnerView.as_view(),
        name="organisation-contact-owner",
    ),
    path(
        "organisation/<int:pk>/favourite/",
        action_view.favourite_organisation,
        name="organisation-favourite",
    ),
    path(
        "organisation/<int:pk>/unsubscribe/",
        action_view.unfavourite_organisation,
        name="organisation-unfavourite",
    ),
    #
    #
    ##############
    ## PROJECTS ##
    ##############
    #
    path("projects/suggest/", suggestion_view.title_suggest, name="title-suggest"),
    path(
        "projects/<int:pk>/update/",
        project.ProjectUpdateView3.as_view(),
        name="project-update",
    ),
    path(
        "projects/<int:pk>/delete/",
        project.ProjectDeleteView.as_view(),
        name="project-delete",
    ),
    path(
        "projects/<int:pk>/history/",
        project.ProjectHistoryView.as_view(),
        name="project-history",
    ),
    path(
        "projects/<int:pk>/", project.ProjectDetailView.as_view(), name="project-detail"
    ),
    path(
        "projects/create/", project.ProjectCreateView.as_view(), name="project-create"
    ),
    path("projects/", project.project_list, name="project-list"),
    #
    #
    ##############
    ## SUBJECTS ##
    ##############
    #
    path("subjects/suggest/", suggestion_view.subject_suggest, name="subject-suggest"),
    path(
        "subjects/create/", subject.SubjectCreateView.as_view(), name="subject-create"
    ),
    path("subjects/", subject.subject_list, name="subject-list"),
    #
    #
    ################
    ## GEOGRAPHIC ##
    ################
    #
    path("geo/create/", address.GeoCreateView.as_view(), name="geo-create"),
    path(
        "addresses/create/", address.AddressCreateView.as_view(), name="address-create"
    ),
    path(
        "addresses/<int:pk>/",
        address.AddressDetailView.as_view(),
        name="address-detail",
    ),
    #
    #
    ###########
    ## LINKS ##
    ###########
    #
    path("links/create/", link.LinkCreateView.as_view(), name="link-create"),
    #
    #
    ##############
    ## KEYWORDS ##
    ##############
    #
    path(
        "keywords/create/", keyword.KeywordCreateView.as_view(), name="keyword-create"
    ),
    #
    #
    ###########
    ## USERS ##
    ###########
    #
    path("favourites/", favourite.FavouriteListView.as_view(), name="user-favourites"),
    path(
        "managed/",
        user.ManagedProjectsListView.as_view(),
        name="user-managed-projects",
    ),
    path(
        "request-contributor-permissions/",
        message.RequestContributorPermissionsView.as_view(),
        name="request-contributor-permissions",
    ),
    path("profile/", user.UserDetailView.as_view(), name="user-detail"),
    path("profile/update/", user.UserUpdateView.as_view(), name="user-update"),
    path("profile/delete/", user.UserDeleteView.as_view(), name="user-delete"),
    #
    #
    ###########################
    ## VISUALS AND ANALYTICS ##
    ###########################
    #
    path("analysis/", page_view.analysis_view, name="analysis"),
    path(
        "visuals/dashboard2/", page_view.visuals_dashboard2, name="visuals-dashboard2"
    ),
    path("visuals/dashboard/", page_view.visuals_dashboard, name="visuals-dashboard"),
    path(
        "visuals/dashboard_experiment",
        page_view.visuals_dashboard_experiment,
        name="visuals-dashboard-experiment",
    ),
    path("visuals/", page_view.visuals, name="visuals-index"),
    path("dashboards/", include("dashboards.urls", namespace="dashboards")),
    #
    #
    ##############################
    ## LANDING PAGE AND SITEMAP ##
    ##############################
    #
    path("", page_view.index, name="index"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

services/web/core/views/keyword.py
from rules.contrib.views import PermissionRequiredMixin
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django_addanother.views import CreatePopupMixin

from ..models import Keyword


class KeywordCreateView(
    PermissionRequiredMixin,
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreatePopupMixin,
    generic.CreateView,
):
    model = Keyword
    permission_required = "core.add_keyword"
    template_name = "keyword_form.html"
    fields = ["text"]
    success_message = "Keyword(s) created."

services/web/core/views/link.py
from rules.contrib.views import PermissionRequiredMixin
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django_addanother.views import CreatePopupMixin

from ..models import ExternalLink


class LinkCreateView(
    PermissionRequiredMixin,
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreatePopupMixin,
    generic.CreateView,
):
    model = ExternalLink
    permission_required = "core.add_link"
    template_name = "link_form.html"
    fields = ["description", "link"]
    success_message = "External link created."

services/web/core/views/organisation.py
from django.urls import reverse
from rules.contrib.views import PermissionRequiredMixin
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django_addanother.views import CreatePopupMixin

from .filter_view import FilteredListView
from ..models import Organisation, OrganisationSubscription
from ..forms import OrganisationForm
from ..filters import OrganisationFilter


class OrganisationCreateView(
    PermissionRequiredMixin,
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreatePopupMixin,
    generic.CreateView,
):
    model = Organisation
    permission_required = "core.add_organisation"
    form_class = OrganisationForm
    template_name = "organisation_form.html"
    success_message = "Organisation created."

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class OrganisationUpdateView(
    PermissionRequiredMixin,
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreatePopupMixin,
    generic.UpdateView,
):
    model = Organisation
    permission_required = "core.change_organisation"
    form_class = OrganisationForm
    template_name = "organisation_form.html"
    success_message = "Organisation updated."


class OrganisationDetailView(generic.DetailView):
    model = Organisation
    template_name = "organisation_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subscriber_ids = OrganisationSubscription.objects.filter(
            organisation=self.get_object()
        ).values_list("user_id", flat=True)
        subscribers = get_user_model().objects.filter(id__in=subscriber_ids)
        context["subscribers"] = subscribers

        return context


class OrganisationListView(FilteredListView):
    model = Organisation
    filterset_class = OrganisationFilter
    template_name = "organisation_list.html"
    paginate_by = 10
    order_by = "name"


class OrganisationDeleteView(
    PermissionRequiredMixin,
    LoginRequiredMixin,
    SuccessMessageMixin,
    generic.DeleteView,
):
    model = Organisation
    template_name = "organisation_delete.html"
    permission_required = "core.delete_organisation"
    success_message = "Organisation deleted"

    def get_success_url(self):
        return reverse("organisation-list")

services/web/core/views/person.py
from django.urls import reverse
from rules.contrib.views import PermissionRequiredMixin
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django_addanother.views import CreatePopupMixin
from extra_views import CreateWithInlinesView
from extra_views import UpdateWithInlinesView
from extra_views import InlineFormSetFactory

from .filter_view import FilteredListView
from ..models import Person, PersonOrganisation, PersonSubscription
from ..forms import PersonOrganisationForm, PersonForm
from ..filters import PersonFilter


class PersonOrganisationInline(InlineFormSetFactory):
    model = PersonOrganisation
    form_class = PersonOrganisationForm


class PersonOrganisationCreateInline(PersonOrganisationInline):
    factory_kwargs = {"extra": 1, "can_delete": False}


class PersonOrganisationUpdateInline(PersonOrganisationInline):
    factory_kwargs = {"extra": 0, "can_delete": True}


class PersonCreateView(
    PermissionRequiredMixin,
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreatePopupMixin,
    CreateWithInlinesView,
):
    model = Person
    permission_required = "core.add_person"

    def get_permission_object(self):
        # Need to return None here as the inlines imply
        # get_object() is not None, but it also has no pk.
        return None

    form_class = PersonForm
    inlines = [PersonOrganisationCreateInline]
    template_name = "person_form.html"
    success_message = "Person added."

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PersonUpdateView(
    PermissionRequiredMixin,
    LoginRequiredMixin,
    SuccessMessageMixin,
    UpdateWithInlinesView,
):
    model = Person
    permission_required = "core.change_person"
    form_class = PersonForm
    inlines = [PersonOrganisationUpdateInline]
    template_name = "person_form.html"
    success_message = "Person updated."


class PersonDeleteView(
    PermissionRequiredMixin,
    LoginRequiredMixin,
    SuccessMessageMixin,
    generic.DeleteView,
):
    model = Person
    template_name = "person_delete.html"
    permission_required = "core.delete_person"
    success_message = "Person deleted"

    def get_success_url(self):
        return reverse("person-list")


class PersonDetailView(generic.DetailView):
    model = Person
    template_name = "person_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subscriber_ids = PersonSubscription.objects.filter(
            person=self.get_object()
        ).values_list("user_id", flat=True)
        subscribers = get_user_model().objects.filter(id__in=subscriber_ids)
        context["subscribers"] = subscribers

        return context


class PersonListView(FilteredListView):
    model = Person
    filterset_class = PersonFilter
    template_name = "person_list.html"
    paginate_by = 10
    order_by = "first_name"

services/web/templates/503.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Maintenance Mode | CoPED</title>
</head>
<body>
{{message|safe|default:"CoPED is down for maintenance. Please check back soon."}}
</body>

services/web/templates/address_detail.html
{% extends "base.html" %}

{% block content %}

<div class="gutters-sm pl-5 pr-5">
    <div class="row">
        <div class="col-md-4">
            {{address}}
        </div>
    </div>
</div>

{% endblock content %}

services/web/templates/address_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %} Address Form {% endblock title %}

{% block content %}

<br><br>
<div class="gutters-sm pl-5 pr-5">
    <div class="row">
        <div class="col-md">
            <h4>Address</h4>
            <p>Please provide details of the address, including the Postcode if known.</p>
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form layout='horizontal' %}
                {% buttons %}
                <button type="submit" value="Update" class="btn btn-primary">{% trans 'Save' %}</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
</div>

{% endblock content %}

services/web/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% load pinax_messages_tags %}
{% load pinax_announcements_tags %}
{% load coped_extras %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Home {% endblock title %} | CoPED</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% include "includes/head.html" %}
  </head>
  <body>

  
    {% if not view.is_popup %}
    <!-- Navigation-->
    <!-- Navigation-->
    <!-- Navigation-->
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">
          <img
            src="{% static 'assets/img/icon_long.png' %}"
            height="30"
            class="d-inline-block align-top"
            alt=""
        /></a>
        <button
          type="button"
          class="navbar-toggler"
          data-toggle="collapse"
          data-target="#navbarCollapse"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <div class="navbar-nav" href="/">
            <div class="d-none d-xl-block">
              <a class="navbar-brand"> Energy Projects Catalogue</a>
            </div>
          </div>
          <div class="navbar-nav ml-auto">
            <a
              class="
                btn
                nav-item
                btn-secondary
                ml-1
                {% block nav_proj %}{% endblock nav_proj %}
              "
              href="{% url 'project-list' %}"
            >
              <i class="fas fa-briefcase"></i> Projects</a
            >
            <a
              class="
                btn
                nav-item
                btn-secondary
                ml-1
                {% block nav_ppl%}{% endblock %}
              "
              href="{% url 'person-list' %}"
            >
              <i class="fas fa-users"></i> People</a
            >
            <a
              class="
                btn
                nav-item
                btn-secondary
                ml-1
                {% block nav_org%}{% endblock %}
              "
              href="{% url 'organisation-list' %}"
            >
              <i class="fas fa-landmark"></i> Organisations</a
            >
            &nbsp;
            <div class="dropdown mr-1">
              <button
                class="btn btn-outline-success dropdown-toggle {% block nav_vis %}{% endblock %}"
                type="button"
                id="dropdownMenuButton3"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                style="max-width: 180px; overflow: hidden; text-overflow: ellipsis"
              >
                <i class="fas fa-chart-pie"></i> Data &amp; Analysis
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton3">
                <a class="dropdown-item" href="{% url 'dashboards:index' %}"><i class="fas fa-info-circle"></i>  Our Dashboards </a>
                <hr class="dropdown-divider" />
                <p class="dropdown-header">
                  <i class="fas fa-toolbox"></i> <b>Login Required</b>
                </p>
                <a class="dropdown-item {% if not user.is_authenticated %}disabled{% endif %}" href="{{metabase_path}}"><i class="fas fa-house-user"></i> Home </a>
                <a class="dropdown-item {% if not user.is_authenticated %}disabled{% endif %}" href="{{metabase_path}}/collection/root"><i class="fas fa-table"></i> Personal Dashboards </a>
                <a class="dropdown-item {% if not user.is_authenticated %}disabled{% endif %}" href="{{metabase_path}}/browse"><i class="fas fa-database"></i> Data Browser </a>
                <a class="dropdown-item {% if not user.is_authenticated %}disabled{% endif %}" href="{{metabase_path}}/question/new"><i class="fas fa-chart-line"></i> Custom Analysis </a>
                <hr class="dropdown-divider" />
                <a class="dropdown-item" href="{% url 'api-root' %}" target="_blank"><i class="fas fa-laptop-code"></i> RESTful API (JSON) </a>
              </div>
            </div>
            <a class="btn nav-item btn-outline-info ml-1 {% block nav_announce %}{% endblock %}" href="{% url 'pinax_announcements:announcement_list' %}">
              <i class="fas fa-bullhorn"></i> Announcements
              {% if not user.is_superuser %}
              {% announcements as announcement_list %}
              <span class="badge badge-pill badge-info">
                {{ announcement_list.count }}
              </span>              
              {% endif %}
            </a>
            &nbsp;
            {% if user.is_authenticated %}
            <div class="dropdown mr-1">
              <button
                class="btn btn-outline-secondary dropdown-toggle"
                type="button"
                id="dropdownMenuButton2"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                style="max-width: 180px; overflow: hidden; text-overflow: ellipsis"
              >
              <i class="fas fa-user"></i> {{ user.username|truncatechars:14 }}
              {% with user|unread_thread_count as unread_messages %}
                {% if unread_messages %}
                <span class="badge badge-pill badge-danger">{{ unread_messages }}</span>
                {% endif %}
              {% endwith %}            
              </button>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                <hr class="dropdown-divider" />
                <p class="dropdown-header">
                <i class="fas fa-user-cog"></i> <b>Account</b>
                </p>
                <a class="dropdown-item" href="{% url 'user-detail' %}"> Profile </a>
                <a class="dropdown-item" href="{% url 'user-managed-projects' %}">
                  My Projects
                    {% if user.project_set.exists %}
                    <span class="badge badge-pill badge-success">{{ user.project_set.count }}</span>
                    {% endif %}
                </a>
                <a class="dropdown-item" href="{% url 'user-favourites' %}">
                  Favourites
                  {% favourite_count user as favourite_count %}
                  {% if favourite_count %}
                    <span class="badge badge-pill badge-secondary">{{ favourite_count }}</span>
                  {% endif %}
                </a>
                <a class="dropdown-item" href="{% url "pinax_messages:inbox" %}">
                  Messages
                  {% with user|unread_thread_count as unread_messages %}
                    {% if unread_messages %}
                      <span class="badge badge-pill badge-danger">{{ unread_messages }}</span>
                    {% endif %}
                  {% endwith %}
                </a>
                <hr class="dropdown-divider" />
                <p class="dropdown-header">
                  <i class="fas fa-user-plus"></i> <b>Network</b>
                </p>
                <a class="dropdown-item" href="{% url 'invitations:send-invite' %}"> Invite a Contact </a>
                {% if user.is_staff %}
                  <hr class="dropdown-divider" />
                  <p class="dropdown-header">
                    <i class="fas fa-cogs"></i> <b>Admin</b>
                  </p>
                  <a class="dropdown-item" href="{% url 'admin:index' %}"> Management </a>
                {% endif %}
                <hr class="dropdown-divider" />
                <a class="dropdown-item" href="{% url 'logout' %}">
                  Log Out <i class="fas fa-sign-out-alt"></i>
                </a>
              </div>
            </div>
            {% else %}
            <div class="mr-1">
              <a
                class="btn btn-primary"
                id="signin_button"
                href="{% url 'login' %}"
              >
                Sign in
              </a>
              <a
                class="btn btn-outline-primary"
                href="{% url 'django_registration_register' %}"
              >
                Sign up
              </a>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <!-- Navigation-->
    <!-- Navigation-->
    <!-- Navigation-->
    <!-- Navigation-->
    {% endif %}




    <article>
      {% bootstrap_messages %}
      {% block content %} {% endblock content %}
      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock pagination %}
    </article>

    {% block footer %}
      {% if not view.is_popup %}
        {% include "includes/footer.html" %}
      {% endif %}
      {% include "includes/footer_scripts.html" %}
    {% endblock footer %}
  </body>
</html>

services/web/templates/geo_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %} Geographic Location Form {% endblock title %}

{% block content %}

<br><br>
<div class="gutters-sm pl-5 pr-5">
    <div class="row">
        <div class="col-md">
            <h4>Location</h4>
            <p>Please provide the latitude and longitude of the address or location.</p>
            <form method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form_errors form %}
                {% bootstrap_form form layout="horizontal" %}
                {% buttons %}
                <button type="submit" value="Update" class="btn btn-primary">{% trans 'Save' %}</button>
                {% endbuttons %}
            </form>
            <p>The following link may help: <a target="_blank" href="https://www.latlong.net/convert-address-to-lat-long.html">https://www.latlong.net/convert-address-to-lat-long.html</a></p>
        </div>
    </div>
</div>

{% endblock content %}

services/web/templates/keyword_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %} Keyword Form {% endblock title %}

{% block content %}

<br><br>
<div class="gutters-sm pl-5 pr-5">
    <div class="row">
        <div class="col-md">
            <h4>Keyword or Key Phrase</h4>
            <p>Please provide a keyword or short phrase to help with search and filtering.</p>
            <form method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form_errors form %}
                {% bootstrap_form form %}
                {% buttons %}
                <button type="submit" value="Update" class="btn btn-primary">{% trans 'Save' %}</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
</div>

{% endblock content %}

services/web/templates/organisation_delete.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block nav_org%}active{% endblock %}

{% block content %}

<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'organisation-list' %}">Organisations</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ organisation.name }}</li>
    </ol>
</nav>

<div class="container col-lg-6">
    <div class="row">
        <div class="col-md">
            <h4>Delete Organisation</h4>
            <p>Please confirm you wish to delete the following organisation.</p>
            <p><strong>Name:</strong> <em>{{organisation.name}}</em></p>
            <form method="post" class="form">
                {% csrf_token %}
                {% buttons %}
                <button type="submit" value="Delete" class="btn btn-danger">{% trans 'Confirm' %}</button>
                <a href="{{ organisation.get_absolute_url }}" class="btn btn-warning">{% trans 'Cancel' %}</a>
                {% endbuttons %}
            </form>
        </div>
    </div>
</div>

{% endblock content %}

services/web/templates/person_formOLD.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load i18n %}

{% block title %} Person Form {% endblock title %}

{% block content %}

<br><br>
<div class="container col-lg-8">
    <div class="row">
        <div class="col-md">
            <h4>Create New Person</h4>
            <form method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form layout="horizontal" %}
                {% buttons %}
                <button type="submit" value="Save" class="btn btn-primary">{% trans 'Save' %}</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
</div>

{% endblock content %}